apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-worker
  labels:
    app: scraper-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scraper-worker
  template:
    metadata:
      labels:
        app: scraper-worker
    spec:  
      containers:
      - name: scraper-api
        image: xiori007/scraper-worker
        ports:
          - containerPort: 5000